server:
  port: 8080
spring:
  application:
    name: AI-HUB-STUDY
  datasource:
    url: jdbc:mysql://localhost:3306/lms_ai?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # chú ý: chỉ dùng update trong lúc phát triển, sau chuyển thành validate hoặc none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
